#######################################################
# 
# configFileManager.py
# Python implementation of the Class ConfigFileManager
# Generated by Enterprise Architect
# Created on:      24-May-2016 12:59:39
# Original author: Jane
# 
#######################################################

import lxml

"""
NAME
    configFileManager - implementation of class
FILE
    configFileManager.py
CLASSES
    ConfigFileManager

NOT YET IMPLEMENTED
"""


class ConfigFileManager:
    """
    Class to set the configuration from a saved file possibly in XML.

    Methods defined here:
        load_XML(...)
            Read in saved configuration info.

        dump_XML(...)
            Write configuration details to file.

        get_config(...)

    ----------------------------------------------------------------------
    No data or other attributes defined here.
    """

    def __init__(self):
        """

        :return: no return
        """
        self.m_product = ""
        self.m_tile = ""
        self.m_year = ""
        self.m_DoY = []

    def load_XML(self):
        """
        Read in saved configuration info.
        If there isn't any, then pass exception up to caller.
        :return: no return
        """
        try:
            open('land_cover_config.xml')
            # if it opens, check whether it's complete
            # set the member variables
        except:
            raise
        else:
            # read in config
            pass

    def dump_XML(self):
        """
        Write configuration details to file.
        Can be used by Configuration class to save current details.

        :return: no return
        """
        pass

    def get_config(self):
        """

        :return: retrieved settings
        """
        return self.m_product, self.m_tile, self.m_year, self.m_DoY
